export type Category =
  | "Light & shadow"
  | "Particles & motion"
  | "Materials & magic"
  | "World building"
  | "Camera & post"
  | "Art styles";
export interface Effect {
  id: string;
  name: string;
  category: Category;
  tagline: string;
  description: string;
  technique: string;
  game: [string, string];
  world: [string, string];
  controls: [string, string, string, string];
  defaults: [number, number, number, number];
  prompt: string;
  cost: string;
  code: string;
}

export const categories: Category[] = [
  "Light & shadow",
  "Particles & motion",
  "Materials & magic",
  "World building",
  "Camera & post",
  "Art styles",
];

type Entry = [
  string,
  string,
  Category,
  string,
  string,
  string,
  [string, string],
  [string, string],
  [string, string, string, string],
  string,
  string,
];
const entries: Entry[] = [
  [
    "soft-shadows",
    "Soft shadows",
    "Light & shadow",
    "A little light. A lot of atmosphere.",
    "Move your pointer to carry a light around the scene. Objects block its path, and the shadow becomes softer farther from the object. Try a larger light to turn crisp silhouettes into broad, soft shadows.",
    "A signed distance field describes each obstacle. The fragment shader marches along the line to the light and estimates how much of an area light is visible. This is a 2D approximation, not a 3D shadow map.",
    [
      "Lantern in the ruins",
      "Carry a lantern through a forest platformer. Rocks and tree trunks cast shadows over the ground.",
    ],
    ["Desk lamp", "A moving lamp illuminates a tiled room. Boxes block it, just as furniture blocks light."],
    ["Light strength", "Light radius", "Animation speed", "Shadow softness"],
    "Add a pointer-controlled lantern with soft 2D shadows cast by rocks and trees.",
    "float visibility = softShadow(pixel, light);\ncolor *= ambient + lightColor * visibility;",
  ],
  [
    "normal-lighting",
    "Normal-map lighting",
    "Light & shadow",
    "Flat sprites, dimensional surfaces.",
    "A flat surface can appear rounded when every pixel has its own surface direction. Move the light to see ridges, circles, and bevels react. The silhouette stays completely flat.",
    "The demo derives normals from a procedural height field with finite differences. A dot product between that normal and the light direction gives diffuse lighting; a reflected light vector adds a specular highlight. Games often store the same directions in a normal-map texture.",
    ["Embossed stone", "Raised rock faces and a rounded character catch the lantern light."],
    ["Brushed metal", "A patterned tiled surface catches glossy highlights as the light moves."],
    ["Light strength", "Surface frequency", "Animation speed", "Relief depth"],
    "Light my 2D sprites with normal maps and adjustable specular highlights.",
    "vec3 normal = normalize(vec3(-dHeightDx, -dHeightDy, 1.0));\nfloat diffuse = max(dot(normal, lightDirection), 0.0);",
  ],
  [
    "bloom",
    "Bloom & glow",
    "Light & shadow",
    "Let bright things spill beyond their edges.",
    "Bright rings, windows, and collectibles bleed light into nearby pixels. Raise the glow and spread independently. Compare with the original to see why a simple bright color alone cannot produce this halo.",
    "The renderer extracts bright pixels into a texture, applies a horizontal Gaussian blur and a vertical blur, then adds the result to the scene. Half-float render targets retain values above 1 when supported; the fallback uses regular color textures.",
    ["Glowing collectibles", "Luminous gems and a magical portal brighten a dark forest."],
    ["Neon after dark", "Windows and colored signage glow against a night-time city."],
    ["Glow strength", "Glow spread", "Animation speed", "Highlight threshold"],
    "Give collectibles and portals an HDR bloom pass with adjustable threshold and radius.",
    "bright = max(scene - threshold, 0.0);\nglow = blurY(blurX(bright));\ncolor = scene + glow * strength;",
  ],
  [
    "god-rays",
    "Light shafts",
    "Light & shadow",
    "Make the air part of the scene.",
    "Sunbeams fan out through the scene. Their direction follows your pointer. The streaks suggest dust or mist catching light, even though the image is still 2D.",
    "A procedural angular occlusion pattern creates radial shafts. Layered noise breaks up their intensity. This inexpensive artistic approximation avoids a volumetric simulation; a production variant can sample a real occlusion buffer.",
    ["Forest canopy", "Slanted beams fall between trees and give the clearing depth."],
    ["Morning through blinds", "Light streaks pass across a city facade like sunlight through a window."],
    ["Beam brightness", "Beam frequency", "Drift speed", "Mist density"],
    "Add animated shafts of sunlight through the forest canopy, modulated by drifting mist.",
    "float rays = pow(max(sin(angle * frequency), 0.0), 8.0);\ncolor += sunColor * rays * mist;",
  ],
  [
    "ambient-occlusion",
    "Contact shadows",
    "Light & shadow",
    "The small shadows that ground a world.",
    "Objects darken the space immediately around them. These close-contact shadows make shapes feel connected to their surroundings. Increase the radius to see how quickly the effect becomes stylized.",
    "The shader evaluates distance to nearby shapes and converts that distance into a local darkening factor. It is a screen-space, distance-field approximation to ambient occlusion, rather than a physical bounce-light simulation.",
    ["Grounded rocks", "Dark contact bands anchor boulders and platforms to the forest floor."],
    ["Objects on a surface", "Small shadows separate a patterned surface from the objects resting on it."],
    ["Shadow strength", "Contact radius", "Animation speed", "Falloff"],
    "Add subtle contact shadows under props and along platform edges.",
    "float occlusion = exp(-abs(distanceToShape) / radius);\ncolor *= 1.0 - occlusion * strength;",
  ],
  [
    "particles",
    "GPU particles",
    "Particles & motion",
    "Thousands of tiny things, one big impression.",
    "Thousands of individual particles orbit the pointer. Every particle has a position, velocity, age, and seed. Change the population and size; the CPU does not update each particle.",
    "WebGL2 transform feedback runs a vertex shader to update particle state into a second buffer. The buffers swap every step. Instanced quads then draw the particles with one draw call and additive blending.",
    ["Magic fireflies", "A swarm of sparks floats around the hero and responds to your pointer."],
    ["Dust in the air", "Glowing motes drift over a night city."],
    ["Particle population", "Particle size", "Simulation speed", "Swirl force"],
    "Add a GPU-simulated firefly swarm attracted to the cursor, with instanced rendering.",
    "nextVelocity += flow(position, pointer) * dt;\nnextPosition += nextVelocity * dt;\n// Capture results with transform feedback.",
  ],
  [
    "trails",
    "Persistent trails",
    "Particles & motion",
    "Draw with the memory of motion.",
    "Particles leave luminous paths behind them. The image remembers earlier frames and gradually forgets them. Move the pointer to paint sweeping curves, or reduce persistence for a sharper swarm.",
    "Two framebuffer textures alternate. Each new frame combines the current particles with a faded copy of the previous frame. This feedback technique is also useful for motion echoes, paint accumulation, and ghost effects.",
    ["Spell ribbons", "Magical sparks draw long ribbons as they move around the clearing."],
    ["Long exposure", "Moving points of light leave photographic trails above a city."],
    ["Particle population", "Particle size", "Simulation speed", "Trail persistence"],
    "Give spell particles fading framebuffer trails that accumulate over time.",
    "history = max(current, previousFrame * persistence);\n// Swap history textures after each frame.",
  ],
  [
    "flow-field",
    "Flow fields",
    "Particles & motion",
    "Turn a vector field into living motion.",
    "Particles follow smoothly varying currents. The pointer bends the flow into a vortex. Fine-scale flow makes turbulent scribbles; broad flow creates sweeping rivers of light.",
    "The update shader evaluates sine-based vector fields at each particle position and adds a pointer vortex. Transform feedback stores the integrated positions and velocities. This is a field-driven particle simulation, not a fluid solver.",
    ["Spirit current", "Energy follows invisible currents through the forest."],
    ["Wind visualization", "Tracer particles reveal large, changing currents over a city."],
    ["Particle population", "Flow scale", "Simulation speed", "Vortex strength"],
    "Animate GPU particles along a smooth flow field with a pointer-controlled vortex.",
    "vec2 field = vec2(sin(p.y * scale + time), cos(p.x * scale));\nvelocity = mix(velocity, field, dt);",
  ],
  [
    "fire",
    "Fire & smoke",
    "Particles & motion",
    "Noise, heat, and a convincing flame.",
    "A turbulent flame rises and thins out as it climbs. The same layered noise forms a cooler plume of smoke above it. No fire footage or animation frames are involved.",
    "Several octaves of interpolated noise move upward at different rates. A tapered envelope shapes the flame; a temperature-like color ramp goes from red to yellow. A separate broad, low-contrast envelope creates smoke.",
    ["Campfire", "A procedural campfire flickers beside the hero and smoke rises above it."],
    ["Furnace glow", "A concentrated hot plume lights a small area of a city scene."],
    ["Flame height", "Turbulence scale", "Rise speed", "Smoke density"],
    "Create a procedural campfire shader with layered noise, hot color gradients, and drifting smoke.",
    "float flame = envelope(p) - fbm(p - vec2(0, time));\ncolor += heatRamp(flame) * flame;",
  ],
  [
    "weather",
    "Rain & snow",
    "Particles & motion",
    "Weather that changes the whole mood.",
    "GPU particles fall across the scene. Change the flake size and wind, then switch contexts: the city uses streak-like rain and the forest uses snow. The particles wrap around the viewport.",
    "Transform feedback integrates gravity and horizontal wind. Instanced billboards stretch vertically for rain and remain soft circles for snow. Additive blending keeps the demonstration simple; alpha blending is often better for opaque snow.",
    ["Snowy clearing", "Snowflakes drift in front of a forest platformer."],
    ["City rain", "Thin rain streaks fall over illuminated buildings."],
    ["Weather density", "Flake / drop size", "Fall speed", "Wind strength"],
    "Add adjustable GPU snow and rain with wind, instanced billboards, and viewport wrapping.",
    "velocity = vec2(wind, -fallSpeed);\nposition = wrap(position + velocity * dt);",
  ],
  [
    "water",
    "Water & refraction",
    "Materials & magic",
    "A whole world in a moving reflection.",
    "The lower part of the scene becomes water. It reflects a vertically flipped view and refracts the scene through animated waves. The bright curved patterns suggest sunlight focused by waves.",
    "A fragment shader changes texture coordinates with layered sine waves, samples a flipped scene texture for reflection, and adds procedural caustics. This is a screen-space surface effect; it does not simulate water volume.",
    ["Forest lake", "Trees and glowing gems reflect in a rippling lake below the platforms."],
    ["Harbor reflections", "City windows stretch and shimmer on the water."],
    ["Wave strength", "Wave frequency", "Wave speed", "Caustic brightness"],
    "Render a reflective 2D lake with animated UV refraction and procedural caustics.",
    "vec2 distorted = uv + waveNormal * strength;\ncolor = mix(waterTint, texture(scene, reflectedUV), reflection);",
  ],
  [
    "ripples",
    "Interactive ripples",
    "Materials & magic",
    "Every touch sends out a wave.",
    "Click or tap the canvas to send a circular wave outward. Move the pointer to relocate the source. A continuous faint wave makes the distortion visible before your first click.",
    "Distance from the click creates a radial phase. A decaying ring displaces scene texture coordinates along the radial direction. This is an analytic ripple, not a grid-based water simulation.",
    ["Pond footsteps", "A splash spreads through the lake below the forest."],
    ["Raindrop rings", "A circular disturbance warps reflected city lights."],
    ["Ripple amplitude", "Ring frequency", "Wave speed", "Ring width"],
    "Spawn expanding, decaying UV-distortion ripples when the player touches water.",
    "float wave = sin(distance * frequency - time * speed);\nuv += radialDirection * wave * envelope;",
  ],
  [
    "heat-haze",
    "Heat haze",
    "Materials & magic",
    "Bend the air without drawing the air.",
    "The view shimmers as if hot air is rising in front of it. Distortion grows toward the lower part of the image. Small settings are convincing; large ones become a dreamlike warp.",
    "Layered animated noise shifts texture coordinates, while a vertical mask limits the effect. Sampling the already-rendered scene makes every object behind the hot air distort together.",
    ["Lava air", "The forest floor radiates enough heat to warp nearby rocks and trees."],
    ["Hot pavement", "City details wobble through rising warm air."],
    ["Distortion strength", "Noise frequency", "Rise speed", "Heat height"],
    "Add screen-space heat distortion above lava with animated noise and a vertical falloff.",
    "uv.x += fbm(uv * scale - time) * heatMask * strength;",
  ],
  [
    "glass",
    "Frosted glass",
    "Materials & magic",
    "The surface changes what is behind it.",
    "A movable pane refracts and blurs the scene behind it. The beveled edge catches light, and fine noise gives the pane a frosted texture. Move the pointer to slide the glass around.",
    "A signed-distance rounded rectangle masks the effect. A blurred scene texture supplies frosting, displaced UVs supply refraction, and the distance gradient supplies an edge highlight.",
    ["Ice shield", "A translucent shield distorts the forest behind the player."],
    ["Frosted window", "A glass panel softens the city behind it."],
    ["Frost opacity", "Blur radius", "Animation speed", "Refraction"],
    "Create a movable frosted-glass shield with background blur, refraction, and a bright bevel.",
    "color = mix(scene, blurredScene(refractedUV), glassMask);",
  ],
  [
    "dissolve",
    "Dissolve",
    "Materials & magic",
    "Disappear one fragment at a time.",
    "A noise threshold erases the image in irregular islands. A bright rim marks the disappearing edge. Sweep the threshold to control the transition precisely.",
    "The shader compares procedural noise against a threshold. Pixels below it become background; pixels just above it receive an emissive edge color. In a sprite shader the same mask can discard fragments or lower alpha.",
    ["Teleport away", "The forest and hero break into glowing fragments as a teleport transition."],
    ["Weathered reveal", "A city image appears through an irregular, burned-paper-like mask."],
    ["Dissolve progress", "Noise scale", "Animation speed", "Edge width"],
    "Dissolve enemies using a noise threshold and a glowing burn rim.",
    "float edge = noise(uv) - progress;\nalpha = step(0.0, edge);\ncolor += glowColor * (1.0 - smoothstep(0.0, width, edge));",
  ],
  [
    "hologram",
    "Holograms",
    "Materials & magic",
    "A signal with just enough imperfection.",
    "The scene becomes a cyan projection with scan bands, flicker, and occasional horizontal interference. The glowing grid is intentionally an artistic signal effect.",
    "The post shader remaps brightness into cyan, multiplies it by moving scan lines, and offsets horizontal strips with seeded noise. Bloom adds a luminous halo.",
    ["Ghost companion", "A forest scene becomes a spectral projection."],
    ["Projected city", "A city model flickers like a holographic planning table."],
    ["Signal strength", "Scan density", "Flicker speed", "Interference"],
    "Make a cyan hologram shader with moving scanlines, occasional strip glitches, and bloom.",
    "color = cyan * luminance(scene) * scanline;\nuv.x += stripNoise * interference;",
  ],
  [
    "parallax",
    "Layered parallax",
    "World building",
    "Depth without a third dimension.",
    "Several landscape layers scroll at different speeds. Distant ridges barely move while the foreground moves quickly. Move the pointer to change the camera offset.",
    "Each procedural layer samples world coordinates with a different camera multiplier. This is the same relationship used by parallax sprite backgrounds: layer position equals camera position times a depth factor.",
    ["Scrolling forest", "Distant mountains, middle trees, and near ground move at different rates."],
    ["City depth", "Building silhouettes form multiple layers moving at different speeds."],
    ["Camera travel", "Landscape scale", "Scroll speed", "Layer separation"],
    "Build a side-scrolling background with four parallax layers and pointer-controlled camera drift.",
    "layerUV.x += cameraX * depthFactor;\ncolor = mix(color, layerColor, layerMask);",
  ],
  [
    "wind",
    "Wind & foliage",
    "World building",
    "A world that breathes around the player.",
    "Blades of grass bend in a traveling gust. Tree branches sway gently, and the motion is strongest at the tips. Watch how scale changes the spacing of the gusts.",
    "The shader shifts each blade horizontally by a sine wave multiplied by height squared. Roots therefore stay fixed. Different phase offsets keep neighboring plants from moving identically.",
    ["Windy meadow", "Grass bends along the platforms and trees sway in the clearing."],
    ["Reeds by the harbor", "Tall blades form a wind visualization in front of city silhouettes."],
    ["Wind amplitude", "Gust frequency", "Gust speed", "Blade height"],
    "Animate foliage with position-dependent wind and a root-to-tip bend mask.",
    "bladeX += sin(time + rootX * frequency) * height * height * wind;",
  ],
  [
    "terrain",
    "Distance-field terrain",
    "World building",
    "Smooth caves from a tiny equation.",
    "A continuous procedural contour becomes terrain. Change its frequency to move from rolling hills to rough caves. The rock texture follows the shape without a mesh.",
    "A height function combines sine waves and fractal noise. The fragment shader compares each pixel to that contour and shades the distance to its edge. This visual demo has no physics; gameplay collision would sample the same field on the CPU or in a physics system.",
    ["Cave floor", "A rough contour creates traversable-looking terrain with lit edges."],
    ["Geological section", "Layered bands resemble a cutaway through rock."],
    ["Terrain height", "Terrain frequency", "Evolution speed", "Rock layers"],
    "Generate editable 2D terrain from a distance field and use the same field for collision queries.",
    "float distance = p.y - terrainHeight(p.x);\ncolor = distance < 0.0 ? rock : sky;",
  ],
  [
    "tilemap",
    "Tilemaps & atlases",
    "World building",
    "Build a world out of reusable pieces.",
    "Repeated tiles assemble a dungeon or decorative floor. The source is a small, locally generated texture atlas. Change the tile size to see how one texture fills a much larger scene.",
    "The fragment shader converts world coordinates into a tile index and a coordinate within the tile. It samples the relevant region of the atlas with nearest filtering. Games normally load the tile IDs from a map texture or instance buffer.",
    ["Dungeon floor", "Stone and grass atlas cells repeat below the forest hero."],
    ["Mosaic surface", "Reusable patterned tiles cover a surface in front of a city."],
    ["Tile coverage", "Tile density", "Animation speed", "Tile variation"],
    "Render a scrolling tilemap from a texture atlas with nearest filtering and reusable tile IDs.",
    "vec2 tileUV = fract(worldUV * tileCount);\nvec2 atlasUV = (tileUV + tileIndex) / atlasGrid;",
  ],
  [
    "sprites",
    "Sprite animation",
    "World building",
    "Give a tiny character a personality.",
    "A pixel character cycles through four walking poses from a generated sprite sheet. The frame rate and scale are independent of the display refresh rate. This scene also shows the sheet frames above the main character.",
    "The shader selects an atlas cell using floor(time times frames per second). Nearest filtering preserves sharp pixel edges. A real game would choose rows for idle, walk, attack, and other animation states.",
    ["Forest adventurer", "A looping pixel hero walks through the clearing."],
    ["Animated sign", "A pixel mascot animates against a city backdrop."],
    ["Character visibility", "Character scale", "Walk cycle speed", "Frame stepping"],
    "Animate a pixel-art hero from a sprite atlas with independent animation speed and nearest filtering.",
    "int frame = int(floor(time * fps)) % frameCount;\ncolor = texture(atlas, frameUV(frame, localUV));",
  ],
  [
    "day-night",
    "Day / night cycle",
    "World building",
    "One scene, a completely different feeling.",
    "The sky, distant scenery, sun, and moon change together. Use the time slider to choose a time of day. Animation gently moves the cycle around that starting point.",
    "A cyclic scalar blends day and night palettes and drives sun/moon positions. Foreground colors receive ambient light from the same cycle. This is palette-based lighting, not a physically simulated atmosphere.",
    ["A day in the forest", "Sunrise and moonlight transform the same platformer background."],
    ["City hours", "The sky cycles while windows become more visible at night."],
    ["Time of day", "Sky contrast", "Cycle speed", "Star brightness"],
    "Add a day-night cycle that synchronizes ambient tint, sky palette, sun, moon, and stars.",
    "float daylight = 0.5 + 0.5 * sin(timeOfDay);\ncolor = mix(nightPalette, dayPalette, daylight);",
  ],
  [
    "shockwave",
    "Shockwaves",
    "Camera & post",
    "Make an impact travel through the image.",
    "Click to release an expanding distortion ring. Objects inside the ring remain in place while the edge bends sharply. It is a camera effect that makes a hit feel much larger.",
    "The shader measures distance from the click and builds a narrow envelope around an expanding radius. That envelope displaces the scene texture radially and adds a bright rim. The ring fades as it expands.",
    ["Heavy landing", "A shockwave ripples away from a hit in the clearing."],
    ["Sonic pulse", "An expanding pulse bends building silhouettes and windows."],
    ["Impact strength", "Ring width", "Expansion speed", "Rim brightness"],
    "Trigger a decaying radial screen-space shockwave on heavy hits, centered on the impact.",
    "float ring = exp(-pow((distance - radius) / width, 2.0));\nuv += direction * ring * strength;",
  ],
  [
    "chromatic",
    "Chromatic aberration",
    "Camera & post",
    "Split a color into three little worlds.",
    "Red, green, and blue channels sample slightly different positions. Increase the strength to see separated colored fringes. The effect grows toward the edges of the screen.",
    "Three texture samples use offsets along the vector from the image center. Each contributes one color channel. Subtle aberration can suggest a lens; stronger settings suit damage or supernatural transitions.",
    ["Damage feedback", "The forest view splits into colored edges during an imagined heavy hit."],
    ["Imperfect lens", "High-contrast windows show colored optical fringes."],
    ["Channel separation", "Edge falloff", "Pulse speed", "Pulse depth"],
    "Add radial RGB channel separation that briefly pulses on damage.",
    "color.r = texture(scene, uv + offset).r;\ncolor.g = texture(scene, uv).g;\ncolor.b = texture(scene, uv - offset).b;",
  ],
  [
    "blur",
    "Focus & blur",
    "Camera & post",
    "Tell the eye where to look.",
    "A sharp band follows your pointer while the rest of the image blurs. Adjust the focus width and blur radius. This is a stylized depth cue, useful for foreground fog or miniature scenes.",
    "Two Gaussian blur passes create a softened scene. A vertical distance mask blends the original and blurred textures. The demo uses screen position as focus depth, not a real depth buffer.",
    ["Focus on the hero", "Platforms outside the pointer-controlled focus band become soft."],
    ["Miniature city", "A tilt-shift-like band makes the city resemble a small model."],
    ["Blur strength", "Blur radius", "Animation speed", "Focus width"],
    "Add a two-pass Gaussian blur and a pointer-controlled sharp focus band.",
    "float blurMask = smoothstep(focusWidth, focusWidth * 2.0, distanceToFocus);\ncolor = mix(scene, blurredScene, blurMask);",
  ],
  [
    "color-grade",
    "Color grading",
    "Camera & post",
    "Change the story with a palette.",
    "A warm highlight and cool shadow treatment changes the scene mood. The controls tune saturation, contrast, and the strength of the grade. Compare the same geometry before and after.",
    "The shader computes luminance, mixes toward or away from gray, applies contrast around middle gray, and tints shadows and highlights separately. Large projects often replace these operations with a lookup-table texture.",
    ["Cinematic forest", "Cool shadows and warm highlights create a fantasy film look."],
    ["Golden-hour city", "Warm windows and teal shadows recolor the city."],
    ["Grade strength", "Saturation", "Animation speed", "Contrast"],
    "Add a controllable teal-and-orange grade with saturation and contrast adjustments.",
    "color = mix(vec3(luma), color, saturation);\ncolor = (color - 0.5) * contrast + 0.5;",
  ],
  [
    "vignette",
    "Vignette & film grain",
    "Camera & post",
    "A subtle frame around the feeling.",
    "Corners darken while small animated specks add film-like texture. Vignette width changes how much of the scene remains bright. Grain is deliberately subtle at the default setting.",
    "A smooth radial mask attenuates the image edges. Seeded per-pixel noise adds zero-centered grain. This is a post-process and does not change object lighting.",
    ["Haunted forest", "A dark perimeter focuses attention on the hero and lantern."],
    ["Film photograph", "The city takes on lens falloff and animated film grain."],
    ["Vignette strength", "Bright area", "Grain speed", "Grain amount"],
    "Add adjustable corner falloff and animated film grain as a final camera pass.",
    "color *= 1.0 - smoothstep(innerRadius, outerRadius, radius);\ncolor += (hash(pixel + time) - 0.5) * grain;",
  ],
  [
    "glitch",
    "Digital glitch",
    "Camera & post",
    "A beautifully broken signal.",
    "Horizontal strips jump, colors split, and intermittent interference breaks the scene. Frequency controls how often strips change. Turn down the amount for brief, controlled impact effects.",
    "A seeded hash selects horizontal bands and computes a time-dependent offset. RGB channels then sample different offsets, with occasional inversion and scanline attenuation. This is deterministic procedural interference.",
    ["Corrupted world", "A forest view fragments as if a simulation is failing."],
    ["Broken broadcast", "A city feed develops strip errors and color separation."],
    ["Glitch amount", "Band density", "Glitch speed", "Color separation"],
    "Create a seeded digital-glitch transition with horizontal displacement and RGB splitting.",
    "float band = floor(uv.y * bandCount);\nuv.x += hash(vec2(band, frame)) * glitchMask;",
  ],
  [
    "pixel-art",
    "Pixel art",
    "Art styles",
    "Less resolution, more character.",
    "The entire scene snaps to a coarse virtual pixel grid, then uses a limited color palette. The sprite sheet already contains native pixel art; this screen effect also pixelates smooth shapes.",
    "Texture coordinates are quantized before sampling, and color channels are quantized afterward. This intentionally changes virtual resolution rather than merely placing a grid over a smooth image.",
    ["Retro platformer", "A forest and pixel hero become a low-resolution console scene."],
    ["Pixel skyline", "Buildings and reflections reduce to small blocks of color."],
    ["Pixelation strength", "Pixel size", "Animation speed", "Palette reduction"],
    "Render my game at a configurable virtual resolution with nearest sampling and a limited palette.",
    "vec2 pixelUV = (floor(uv * virtualSize) + 0.5) / virtualSize;\ncolor = floor(texture(scene, pixelUV) * levels) / levels;",
  ],
  [
    "toon",
    "Cel shading",
    "Art styles",
    "Bold shapes. Deliberate color.",
    "Continuous gradients become distinct bands, with dark contours around objects. More bands preserve detail; fewer make the scene read like a cartoon.",
    "The post shader quantizes colors into a configurable number of bands. Neighboring scene samples estimate edge contrast and darken contours. It is a 2D color treatment, not a 3D toon material.",
    ["Cartoon adventure", "Forest props gain strong color bands and dark silhouettes."],
    ["Animated city", "Building silhouettes become graphic, outlined shapes."],
    ["Cel strength", "Color bands", "Animation speed", "Outline weight"],
    "Give the 2D scene quantized cel colors and contrast-based contour outlines.",
    "color = floor(color * bands + 0.5) / bands;\ncolor *= 1.0 - edgeContrast * outlineStrength;",
  ],
  [
    "watercolor",
    "Watercolor",
    "Art styles",
    "Pigment, paper, and a softer edge.",
    "Colors bleed slightly into their surroundings and a paper-like texture breaks up the fill. The effect imitates a watercolor illustration using only procedural noise and texture samples.",
    "Fine noise distorts sampling coordinates; a blurred scene approximates pigment spread. Layered noise modulates color like paper grain. This is a stylistic approximation, not a physical pigment-and-water simulation.",
    ["Painted storybook", "The forest becomes a soft, textured storybook scene."],
    ["Urban sketch", "City blocks soften into a loose painted illustration."],
    ["Paint strength", "Bleed radius", "Animation speed", "Paper grain"],
    "Make a watercolor treatment using subtle UV wobble, pigment bleed, and paper-grain modulation.",
    "paint = mix(scene, blurredScene, bleed);\ncolor = paint * (0.9 + paperNoise * 0.1);",
  ],
  [
    "ink",
    "Ink & hatching",
    "Art styles",
    "Let the contours do the talking.",
    "Color gives way to a warm paper background, dark contours, and fine diagonal hatching. Darker parts of the image receive more ink.",
    "Neighboring texture samples estimate edges. Luminance controls how much procedural crosshatching appears. A paper-tinted background and monochrome ink finish the effect.",
    ["Illustrated quest", "A forest level becomes a pen-and-ink map-like illustration."],
    ["Architectural sketch", "The skyline becomes a hatched line drawing."],
    ["Ink strength", "Hatch density", "Animation speed", "Contour weight"],
    "Create a pen-and-ink post-process with edge detection and luminance-dependent crosshatching.",
    "ink = edgeMagnitude + hatchPattern * (1.0 - luma);\ncolor = mix(paper, inkColor, ink);",
  ],
  [
    "paper",
    "Paper cutout",
    "Art styles",
    "Layer a world like a little theater.",
    "Colors flatten into a small palette and shifted silhouettes create paper-layer shadows. Fine noise makes the flat fills resemble paper. The parallax context makes the layered construction easiest to read.",
    "Color quantization flattens shading. An offset neighboring texture sample darkens the exposed side of silhouettes, approximating a paper shadow. Noise adds material texture.",
    ["Paper forest", "Mountains and trees become layered colored-paper scenery."],
    ["Cutout skyline", "Building silhouettes look like stacked paper shapes."],
    ["Cutout strength", "Shadow offset", "Animation speed", "Paper texture"],
    "Give parallax layers flat paper colors, small offset silhouette shadows, and paper grain.",
    "color = quantize(scene, 5.0);\ncolor -= silhouetteDifference(offsetUV) * shadow;",
  ],
  [
    "crt",
    "CRT monitor",
    "Art styles",
    "The screen is part of the nostalgia.",
    "The image curves toward the corners, horizontal scan lines darken alternating rows, and red-green-blue phosphor columns add a display texture. Glow softens the brightest parts.",
    "A radial UV warp simulates screen curvature. Sine waves create scanlines and a repeating three-column color mask represents phosphor stripes. Pixels outside the curved screen become dark.",
    ["Arcade cabinet", "A forest game appears on an old curved arcade display."],
    ["Retro surveillance", "A city feed takes on analog monitor texture."],
    ["CRT strength", "Scan density", "Animation speed", "Screen curvature"],
    "Add a CRT pass with curved UVs, scanlines, RGB phosphor stripes, and bloom.",
    "uv = center + offset * (1.0 + curvature * dot(offset, offset));\ncolor *= scanlines * phosphorMask;",
  ],
  [
    "halftone",
    "Comic halftone",
    "Art styles",
    "Print an image one dot at a time.",
    "Dark tones become large ink dots and light tones become small dots. Change dot spacing to watch the same scene turn into different print textures.",
    "The shader measures position within a repeating cell and compares distance from its center to a radius derived from luminance. A warm paper color and dark ink recreate a monochrome print pattern.",
    ["Comic-panel forest", "Forest silhouettes resolve into a comic-book print pattern."],
    ["Newspaper skyline", "City brightness becomes a field of printable dots."],
    ["Print strength", "Dot density", "Animation speed", "Ink coverage"],
    "Render a halftone post-process with dot radius driven by luminance and configurable spacing.",
    "float radius = sqrt(1.0 - luma) * coverage;\nink = 1.0 - smoothstep(radius, radius + aa, cellDistance);",
  ],
  [
    "neon",
    "Neon wire",
    "Art styles",
    "Keep the edges. Turn on the electricity.",
    "Filled objects become electric contours on a dark background. Blue, pink, and lime tones animate across the edges. A blur-based glow makes the lines feel emissive.",
    "The post shader estimates scene edges with neighboring texture samples and colors them with a cycling palette. It also derives soft glow from the blurred scene. It is a screen-space contour effect, not actual mesh wireframes.",
    ["Cyber forest", "Rocks, platforms, and trees become luminous electric outlines."],
    ["Neon city", "Windows and building edges pulse against a dark background."],
    ["Neon strength", "Line width", "Color cycle speed", "Glow halo"],
    "Turn object contours into animated neon outlines with a dark background and a soft glow.",
    "color = neonPalette(position, time) * edgeMagnitude;\ncolor += blurredScene * glow;",
  ],
  [
    "metaballs",
    "Metaballs",
    "Materials & magic",
    "Separate shapes that melt together.",
    "Moving blobs merge when they approach each other. A smooth threshold turns several overlapping fields into one continuous surface. Move the pointer to bring an extra blob into the mix.",
    "Each blob contributes an inverse-square scalar field. The shader sums the fields, thresholds the result, and shades the contour. This is an implicit surface, useful for slime, liquid UI, and soft magic.",
    ["Slime creature", "Merging green blobs float above the forest floor."],
    ["Liquid study", "A fluid-like shape moves against an architectural background."],
    ["Blob radius", "Blob spacing", "Motion speed", "Surface softness"],
    "Build a slime effect from summed metaball fields with smoothly merging contours.",
    "field += radius * radius / dot(pixel - center, pixel - center);\nmask = smoothstep(threshold, threshold + softness, field);",
  ],
  [
    "masks",
    "Masks & portals",
    "Materials & magic",
    "A window into another version of the world.",
    "A circular portal follows the pointer. Inside it, the scene is mirrored and shifted into a different palette. Outside it, the original image remains visible.",
    "A signed-distance circle produces an anti-aliased mask. That mask mixes the base sample with a second, transformed sample. Real games can render a separate destination scene into another texture.",
    ["Magic portal", "A circular window reveals a mirrored spectral forest."],
    ["Lens window", "A movable lens reveals an alternate view of the city."],
    ["Portal blend", "Portal radius", "Animation speed", "Edge feather"],
    "Composite a second render texture through a movable signed-distance portal mask.",
    "float mask = 1.0 - smoothstep(radius, radius + feather, distance);\ncolor = mix(sceneA, transformedSceneB, mask);",
  ],
  [
    "dither",
    "Dither & palette",
    "Art styles",
    "Use a pattern to invent more tones.",
    "A limited palette gains intermediate-looking tones from an ordered dot pattern. Up close you see individual decisions; from farther away the eye blends them.",
    "A 4 by 4 Bayer threshold matrix offsets the quantization boundary for each pixel. A fixed palette maps luminance into dark blue, purple, coral, and cream. Ordered dithering is deterministic and needs no random texture.",
    ["Handheld fantasy", "The forest uses a tiny palette with patterned shading."],
    ["Limited-color poster", "A city image becomes a four-color printed poster."],
    ["Dither strength", "Pattern size", "Animation speed", "Palette contrast"],
    "Apply an ordered Bayer dither and a four-color palette to the scene.",
    "float threshold = bayer4(pixel % 4) / 16.0;\ncolor = palette(floor(luma * 3.0 + threshold));",
  ],
  [
    "instancing",
    "Instanced sprites",
    "Particles & motion",
    "A crowd without a crowd of draw calls.",
    "Thousands of little atlas sprites move independently. Population controls the number of instances. Each sprite shares the same geometry and texture while keeping its own GPU state.",
    "The particle state buffer becomes an instanced vertex attribute. WebGL2 drawArraysInstanced repeats one quad for the whole crowd, and the fragment shader samples animated atlas cells. The same approach can batch foliage, bullets, or crowds.",
    ["Tiny adventurer crowd", "A swarm of pixel heroes moves above the forest scene."],
    ["Animated billboard swarm", "Repeated animated sprites float above the city."],
    ["Sprite population", "Sprite size", "Simulation speed", "Swarm force"],
    "Batch thousands of animated sprites with instanced quads, per-instance state, and one atlas.",
    "gl.vertexAttribDivisor(stateAttribute, 1);\ngl.drawArraysInstanced(gl.TRIANGLE_STRIP, 0, 4, count);",
  ],
];

export const effects: Effect[] = entries.map((e) => ({
  id: e[0],
  name: e[1],
  category: e[2],
  tagline: e[3],
  description: e[4],
  technique: e[5],
  game: e[6],
  world: e[7],
  controls: e[8],
  prompt: e[9],
  code: e[10],
  defaults:
    e[0] === "dissolve"
      ? [0.35, 0.5, 0.4, 0.4]
      : e[0] === "day-night"
        ? [0.3, 0.5, 0.15, 0.5]
        : [0.65, 0.5, 0.5, 0.55],
  cost:
    e[2] === "Particles & motion"
      ? "Scales with particle count and overdraw. Larger translucent particles can cost more than small ones, even at the same count."
      : ["bloom", "blur", "glass", "watercolor", "neon", "hologram", "crt"].includes(e[0])
        ? "Multiple texture passes. Blur works at half resolution to reduce bandwidth. Higher render resolution increases the cost."
        : e[0] === "soft-shadows"
          ? "Up to 32 distance-field steps per pixel. More obstacles or a larger render resolution increase work."
          : "Mostly one fragment operation per pixel after the scene pass. Render resolution and texture sample count determine the cost.",
}));

export const styleOptions = [
  "Original",
  "Pixel art",
  "Cel shading",
  "Watercolor",
  "Ink",
  "Paper cutout",
  "CRT",
  "Halftone",
  "Neon",
  "Dither",
] as const;
